advcbv/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls', namespace='basic_app123'))

]

basic_app/templates/basic_app/urls.py
from django.urls import path,re_path
from . import views

app_name = 'basic_app'

urlpatterns = [
    #
    # path('',views.index),
    # path('base',views.base),
    #path('',views.CBView.as_view())
    path('', views.IndexView.as_view()),
    path('list/', views.SchoolListView.as_view(),name='list'),
    path('list/<int:pk>', views.SchoolDetailView.as_view(),name='sch_detail'),
    path('create/', views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>', views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(),name='delete'),
    # path('register/<int:pk>', views.UserRegisterView.as_view(),name='register'),
    #path('userList/<int:pk>', views.UserListView.as_view(),name='user_list'),
    #re_path(r'^(?P<pk>[-\w]+/$)', views.SchoolDetailView.as_view()),
     path('register/',views.register,name='register'),
     path('createStudent1/', views.StudentCreateView.as_view(),name='createStudent'),
     path('deleteStudent/<int:pk>', views.StudentDeleteView.as_view(),name='student_delete'),
     path('studentDetails/<int:pk>', views.StudentDetailView.as_view(),name='student_detail_URL'),
     path('studentList/',views.StudentListView.as_view(),name='student_list'),
     path('login/',views.user_login,name='login_NS'),
     path('logout/',views.user_logout,name='logout'),


]

basic_app/urls.py
from django.urls import path,re_path
from . import views

app_name = 'basic_app'

urlpatterns = [
    #
    # path('',views.index),
    # path('base',views.base),
    #path('',views.CBView.as_view())
    path('', views.IndexView.as_view()),
    path('list/', views.SchoolListView.as_view(),name='list'),
    path('list/<int:pk>', views.SchoolDetailView.as_view(),name='sch_detail'),
    path('create/', views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>', views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(),name='delete'),
    # path('register/<int:pk>', views.UserRegisterView.as_view(),name='register'),
    #path('userList/<int:pk>', views.UserListView.as_view(),name='user_list'),
    #re_path(r'^(?P<pk>[-\w]+/$)', views.SchoolDetailView.as_view()),
     path('register/',views.register,name='register'),
     path('createStudent1/', views.StudentCreateView.as_view(),name='createStudent'),
     path('deleteStudent/<int:pk>', views.StudentDeleteView.as_view(),name='student_delete'),
     path('studentDetails/<int:pk>', views.StudentDetailView.as_view(),name='student_detail_URL'),
     path('studentList/',views.StudentListView.as_view(),name='student_list'),
     path('login/',views.user_login,name='login_NS'),
     path('logout/',views.user_logout,name='logout'),


]

basic_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class School(models.Model):

    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:sch_detail',kwargs={'pk':self.id})

class Student(models.Model):
    """docstring for ."""
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('basic_app:student_detail_URL',kwargs={'pk':self.id})

    def __str__(self):
        return self.name

class UserProfileInfo(models.Model):

    #create relationship (dont inherit from user!)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    # def get_absolute_url(self):
    #     return reverse('basic_app:register',kwargs={'pk':self.id})

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm (forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    """docstring for ."""

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,ListView,DetailView,
CreateView,UpdateView,DeleteView)
from django.urls import reverse_lazy,reverse

from . import models
# from . import forms
from .forms import UserForm,UserProfileInfoForm

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout

# Create your views here.

# class CBView(View):
#     def get(self,request):
#         return HttpResponse("Class based http response")

class IndexView(TemplateView):
    template_name ='basic_app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'basic injection'

        return context
class SchoolListView(ListView):
    """docstring for  SchoolListView."""
    context_object_name = 'schools'
    model = models.School
    #this returns school_list by default by framework
    print('======school list view is called')
    template_name = 'basic_app/school_list2.html'
    #if template_name is not defined, system will use school_list.html as default html

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    #this by default return school as school details.
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School
    #template_name = ''
    #default system is loooking for school_form.html
class SchoolUpdateView(UpdateView):

    # why i cannot just put one field??
    fields = ('principal',)
    model = models.School
class SchoolDeleteView(DeleteView):
    """docstring for SchoolDeleteView."""
    model = models.School
    success_url = reverse_lazy("basic_app:list")

# class UserRegisterView(CreateView):
#     context_object_name = 'registerProfile'
#     model = models.UserProfileInfo
#     #successful_url = reverse_lazy("basic_app:user_list")
#     template_name = 'basic_app/register.html'

class StudentCreateView(CreateView):

        fields = ('name','age','school')
        model = models.Student
        template_name = 'basic_app/student_form.html'

class StudentDetailView(DetailView):
    context_object_name = 'student_detail'
    model = models.Student
    #this by default return school as school details.
    template_name = 'basic_app/student_detail.html'

class StudentDeleteView(DeleteView):
    model = models.Student
    success_url = reverse_lazy("basic_app:student_list")

class StudentListView(ListView):
    """docstring for StudentList."""
    context_object_name = 'students'
    model = models.Student
    # use default naming, student_list

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']
            else:
                print('-----NOT PROFLE IMAGE found!------')
            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'basic_app/register.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    print(request.POST)
    if request.method == 'POST':
        user_name = request.POST.get('username')
        user_password = request.POST.get('password')


        user = authenticate(username=user_name,password=user_password)

        if user:
            if user.is_active:
                login(request,user)
                print(f'------welcome {user_name}login---------')
                return HttpResponseRedirect(reverse('basic_app:list'))
            else:
                return HttpResponse("uaser account is not active")
        else:
            print("some one tried login but not successful")
            print(f'user name is {user_name}, and passwor is {user_password}')


    return render(request,'basic_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    print('logout is called===')
    return HttpResponseRedirect(reverse('basic_app:login_NS'))

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  </head>
  <body>

    <nav class="nav bar navbar -default navbar-static-top">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</li></a>
          <li><a class="navbar-link" href="{% url 'admin:index'%}"> Admin</li></a>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}"> Register</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:createStudent' %}"> Add New Student</a></li>
          {% if user.is_authenticated %}
          <li><a class="navbar-link" href="{% url 'basic_app:logout' %}"> Hi,Logout</a></li>
          {% else%}
          <li><a class="navbar-link" href="{% url 'basic_app:login_NS' %}">Login</a></li>
          {% endif %}
      </ul>

    </nav>
  <div class="container">
    {% block body_block %}
    <title>this is the base file2</title>
    {% endblock %}
  </div>

  </body>
</html>

basic_app/templates/basic_app/login.html
{% extends "basic_app/basic_app_base.html" %}
{% load staticfiles%}
{% block body_block%}
<div class="jumbotron">
<h1>Please login</h1>
<form action="{% url 'basic_app:login_NS' %}" method="post">
<!-- <form method="post"> -->
  {% csrf_token%}
  <label for="username"> user name</label>
  <input type="text" name="username" value="">
  <label for="password">Enter Password</label>
  <input type="password" name="password" >
  <input type="submit" value="login">

</form>

</div>
{% endblock%}

basic_app/templates/basic_app/register.html
{% extends "basic_app/basic_app_base.html" %}
{% load staticfiles%}
{% block body_block%}

<div class="jumbotron">

  {% if registered %}
  <h1> thank you for your registering!</h1>

  {% else %}
    <h1>Regsiter Here</h1>
    <h3>Please fill in the form below</h3>
    <form method="post">

         {% csrf_token %}
         {{ user_form.as_p }}
         {{ profile_form.as_p }}
      <input type="Submit" class="btn btn-primary" value="Submit">

    {% endif %}
</div>
{% endblock%}

basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block%}
<h1>Delete School {{school.id}}- {{school.name}},PK: {{school.pk}}</h1>
<form  method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app:sch_detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock%}

basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">

  <h1>welcome to school detail page</h1>
    <h2>school details:</h2>

     <p>name: {{school_detail.name}}</p>
     <p>principal:{{school_detail.principal }}</p>
     <p>location:{{school_detail.location }}</p>
     <h3>students</h3>

     {% for student in school_detail.students.all %}
     <p>{{student.name}} is study in {{school_detail.name}} at age {{student.age}}</p>
        {% endfor %}

</div>

<div class="container">
  <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
   <a class='btn btn-danger' href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a>
  </p>

</div>


{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block%}

<h1>
{% if not form.instance.pk %}
  create school
{% else %}
  Update School
{% endif %}
</h1>

<form method="post">

  {% csrf_token %}
  {{ form.as_p }}
  <input type="Submit" class="btn btn-primary" value="Submit">

</form>

{% endblock%}

basic_app/templates/basic_app/school_list2.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block%}
<h1>welcome to a list of all schools</h1>

<ol>
  {% for sch in schools%}
  <h2><li><a href="{{sch.id}}">{{sch.name}}</a></li></h2>

  {% endfor%}
</ol>
<div class="container">
  <h2><a href="{% url 'basic_app:create' %}" </a>Create School</h2>
</div>

{% endblock%}

basic_app/templates/basic_app/student_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block%}
<h1>Delete School {{student.id}}- {{student.name}},PK: {{student.pk}}</h1>
<form  method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app:student_list' %}">Cancel</a>
</form>
{% endblock%}

basic_app/templates/basic_app/student_detail.html
{% extends "basic_app/basic_app_base.html"%}
{%block body_block%}

<div class="jumbotron">
  <h1>New student was created. Student Details:</h1>
     <p>name: {{student_detail.name}}</p>
     <p>age: {{student_detail.age}}</p>
     <p>school: {{student_detail.school}}</p>

</div>

<div class="container">

<p><a class='btn btn-danger' href="{% url 'basic_app:student_delete' pk=student_detail.pk %}">Delete Student</a>


</div></p>


</div>
{%endblock%}

basic_app/templates/basic_app/student_form.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block%}

<form method="post">

  {% csrf_token %}
  {{ form.as_p }}

  <input type="Submit" class="btn btn-primary" value="Add Student">

</form>


{% endblock%}

basic_app/templates/basic_app/student_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block%}
<h1>welcome to a list of all students</h1>

<ol>
  {% for stdt in students%}
  <!-- <h2><li><a href="{url 'basic_app:student_detail_URL' pk=student_detail.pk }">{{stdt.name}}</a></li></h2> -->
  <h2><li><a href="{% url 'basic_app:student_detail_URL' pk=stdt.id %}">{{stdt.name}},stuent ID: {{stdt.id}}</a></li></h2>

  {% endfor%}
</ol>
<div class="container">
  <h2><a href="{% url 'basic_app:createStudent' %}" </a>Create Student</h2>
</div>

{% endblock%}